version: '3.7'

services:
  database:
    container_name: mysql_db
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: zirraforming
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafywlfkvhald
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    ports:
      - 3306:3306
    volumes:
      - "./db/mysql/conf.d:/etc/mysql/conf.d"
      - "./db/mysql/mysql:/var/lib/mysql"
      - "./db/mysql/initdb.d:/docker-entrypoint-initdb.d"
      - "./db/mysql/data:/data"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--lower_case_table_names=1"
    networks:
      - default

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./db/redis:/data"
    command:
      - "--appendonly yes"
    networks:
      - default

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ssafy
      MONGO_INITDB_ROOT_PASSWORD: ssafywlfkvhald
      MONGO_INITDB_DATABASE: zirraforming
      TZ: Asia/Seoul
    volumes:
      - "./db/mongodb/data/db:/data/db"
      - "./db/mongodb/initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - default

  application:
    container_name: spring-boot
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/zirraforming?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - database
      - redis
      - mongodb
    networks:
      - default

networks:
  default: