FROM openjdk:11-jdk

ARG JAR_FILE=./build/libs/*.jar

COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=develop", "-Duser.timezone=Asia/Seoul", "-jar", "/app.jar"]

#ARG JAR_FILE=./build/libs/*.jar
#COPY ${JAR_FILE} app.jar